---
title: "preprocessing"
author: "Sarah Hvid Andersen"
date: "2/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load('dplyr', 'tidyverse')
library(tidyverse)
```


```{r}
df <- read.csv('data/preprocessed/GYM_alle_p.csv', sep = ';', encoding = 'UTF-8')
adress <- read_csv('data/preprocessed/ALL_adresser_p.csv')

```

```{r}


df$got_adress <- ifelse(df$Institutionsnummer %in% adress$Institutionsnummer, 1, 0)

missing <- df %>% filter(got_adress == 0)

unique(missing$Institution)
unique(missing$Institutionsnummer)
```

```{r}

df2$got_adress <- ifelse(df2$Institutionsnummer %in% adress$Institutionsnummer, 1, 0)

missing2 <- df2 %>% filter(got_adress == 0)

unique(missing2$Institution)
unique(missing2$Institutionsnummer)
```

Now, i can merge the datasets:

```{r}

df <- df %>% 
  rename('Hovedomr책de' = 'X.U.FEFF.Hovedomr책de') %>% 
  rename_with( ~ gsub("X", "", .x, fixed = TRUE)) %>% 
  rename_with( ~ gsub(".", "-", .x, fixed = TRUE))

df <- df %>% 
  filter_at(vars(`2012-2013`,`2013-2014`,`2014-2015`, `2015-2016`, `2016-2017`, `2017-2018`, `2018-2019`, `2019-2020`, `2020-2021`, `2021-2022`), any_vars(!is.na(.)))

df3 <- df %>% left_join(adress, by = 'Institutionsnummer')
```

Now, i will try to get the coordinates from the adresses:

```{r}
library(opencage)
library(tidyverse)
library(leaflet)
library(stringr)

df3$location1 <- str_c(df3$Adresse, ', ', df3$Postnummer)
df3$location <- str_c(df3$location1, ' ', df3$By)

locations <- as.data.frame(unique(df3$location))
locations <- locations %>% 
  rename('location' = 'unique(df3$location)')


# see configuration options
#help(oc_config)

# set key in the environment
Sys.setenv(OPENCAGE_KEY = "a7919189d4134270a7d212e72d9ecd82")

# set the key interactively if it is missing.
oc_config('a7919189d4134270a7d212e72d9ecd82')
```

```{r}

s <- oc_forward_df(locations, placename = location, countrycode = "DK", limit =1, no_annotations = TRUE)
GYM_locations <- df3 %>% left_join(s)

#write.csv(GYM_locations,"GYM_locations.csv", row.names = FALSE)

```


repeating the proccess with the EUD educations:

```{r}
df <- read.csv('EUD_grundforlob1_grupper_p.csv', sep = ';', encoding = 'UTF-8')

df <- df %>% 
  rename('Hovedomr책de' = 'X.U.FEFF.Hovedomr책de') %>% 
  rename_with( ~ gsub("X", "", .x, fixed = TRUE)) %>% 
  rename_with( ~ gsub(".", "-", .x, fixed = TRUE))

df <- df %>% 
  filter_at(vars(`2015-2016`, `2016-2017`, `2017-2018`, `2018-2019`, `2019-2020`, `2020-2021`, `2021-2022`), any_vars(!is.na(.)))

df3 <- df %>% left_join(adress, by = 'Institutionsnummer')

df3$location1 <- str_c(df3$Adresse, ', ', df3$Postnummer)
df3$location <- str_c(df3$location1, ', ', df3$By)

locations <- as.data.frame(unique(df3$location))
locations <- locations %>% 
  rename('location' = 'unique(df3$location)')

s2 <- oc_forward_df(locations, placename = location, countrycode = "DK", limit =1, no_annotations = TRUE)
EUD_locations <- df3 %>% left_join(s2)

#write.csv(EUD_locations,"EUD_locations.csv", row.names = FALSE)

```

